/****************************************************************************
  Copyright (c) 2006-2012, Dell Inc
  All rights reserved.
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
  - Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
  - Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
  - Neither the name of Dell Inc nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE. 
****************************************************************************/

//--------------------------------------------------------------------------
// Includes
//--------------------------------------------------------------------------
#include "ipmitool/cssipmix.h"
#include "ipmitool/cssipmi.h"
#include "ipmitool/cssapi.h"
#include "ipmitool/cmnslf.h"

SelStateText EventTable[] = 
{
{"AMP0300",2,"The system board <name> current is less than the lower warning threshold.",0,0},
{"AMP0301",1,"The system board <name> current is less than the lower critical threshold.","System board <name> current is outside of range. Contact Support",3},
{"AMP0302",2,"The system board <name> current is greater than the upper warning threshold.",0,0},
{"AMP0303",1,"The system board <name> current is greater than the upper critical threshold.","System board <name> current is outside of range. Contact Support",3},
{"AMP0304",1,"The system board <name> current is outside of range.","System board <name> current is outside of range. Contact Support",3},
{"AMP0305",3,"The system board <name> current is within range.",0,0},
{"AMP0306",2,"Disk drive bay <name> current is less than the lower warning threshold.",0,0},
{"AMP0307",1,"Disk drive bay <name> current is less than the lower critical threshold.","Disk drive bay <name> current is outside of range. Contact Support",3},
{"AMP0308",2,"Disk drive bay <name> current is greater than the upper warning threshold.",0,0},
{"AMP0309",1,"Disk drive bay <name> current is greater than the upper critical threshold.","Disk drive bay <name> current is outside of range. Contact Support",3},
{"AMP0310",1,"Disk drive bay <name> current is outside of range.","Disk drive bay <name> current is outside of range. Contact Support",3},
{"AMP0311",3,"Disk drive bay <name> current is within range.",0,0},
{"AMP0312",2,"System level current is less than the lower warning threshold.",0,0},
{"AMP0313",1,"System level current is less than the lower critical threshold.","System level current is outside of range. Contact Support",3},
{"AMP0314",2,"System level current is greater than the upper warning threshold.",0,0},
{"AMP0315",1,"System level current is greater than the upper critical threshold.","System level current is outside of range. Contact Support",3},
{"AMP0316",1,"System level current is outside of range.","System level current is outside of range. Contact Support",3},
{"AMP0317",3,"System level current is within range.",0,0},
{"AMP0318",2,"Chassis power level current is less than the lower warning threshold.",0,0},
{"AMP0319",1,"Chassis power level current is less than the lower critical threshold.",0,0},
{"AMP0320",2,"Chassis power level current is greater than the upper warning threshold.",0,0},
{"AMP0321",1,"Chassis power level current is greater than the upper critical threshold.",0,0},
{"AMP0322",1,"Chassis power level current is outside of range.",0,0},
{"AMP0323",3,"Chassis power level current is within range.",0,0},
{"ASR0000",1,"The watchdog timer expired.",0,0},
{"ASR0001",1,"The watchdog timer reset the system.",0,0},
{"ASR0002",1,"The watchdog timer powered off the system.",0,0},
{"ASR0003",1,"The watchdog timer power cycled the system.",0,0},
{"ASR0008",1,"The watchdog timer interrupt was initiated.",0,0},
{"ASR0009",3,"The system returned from a watchdog timer event.",0,0},
{"ASR0100",1,"The BIOS watchdog timer reset the system.",0,0},
{"ASR0101",1,"The OS watchdog timer reset the system.",0,0},
{"ASR0102",1,"The OS watchdog timer shutdown the system.",0,0},
{"ASR0103",1,"The OS watchdog timer powered down the system.",0,0},
{"ASR0104",1,"The OS watchdog timer powered cycle the system.",0,0},
{"ASR0105",1,"The OS watchdog timer powered off the system.",0,0},
{"ASR0106",1,"The OS watchdog timer expired.",0,0},
{"ASR0107",1,"The OS watchdog timer pre-timeout interrupt was initiated.",0,0},
{"ASR0108",3,"The system returned from an OS watchdog timer event.",0,0},
{"BAT0000",2,"The system board battery is low.",0,0},
{"BAT0001",3,"The system board battery is operating normally.",0,0},
{"BAT0002",1,"The system board battery has failed.","System board battery has failed. Check battery",1},
{"BAT0003",3,"The system board battery is present.",0,0},
{"BAT0004",1,"The system board battery is absent.","System board battery is absent. Check battery",1},
{"BAT0005",2,"The storage battery is low.",0,0},
{"BAT0006",3,"The storage battery is operating normally.",0,0},
{"BAT0007",1,"The storage battery has failed.","Storage battery has failed. Check battery.",1},
{"BAT0008",3,"The storage battery is present.",0,0},
{"BAT0009",1,"The storage battery is absent.","Storage battery is absent. Check battery.",1},
{"BAT0010",2,"The storage battery for disk drive bay <bay> is low.",0,0},
{"BAT0011",3,"The storage battery for disk drive bay <bay> is operating normally.",0,0},
{"BAT0012",1,"The storage battery for disk drive bay <bay> has failed.","Battery for disk drive bay <bay> has failed. Check battery.",1},
{"BAT0013",3,"The storage battery for disk drive bay <bay> is present.",0,0},
{"BAT0014",1,"The storage battery for disk drive bay <bay> is absent.","Battery for disk drive bay <bay> is absent. Check battery.",1},
{"BAT0015",2,"The <name> battery is low.",0,0},
{"BAT0016",3,"The <name> battery is operating normally.",0,0},
{"BAT0017",1,"The <name> battery has failed.","The <name> battery has failed. Check battery.",1},
{"BAT0018",3,"The <name> battery is present.",0,0},
{"BAT0019",1,"The <name> battery is absent.","The <name> battery is absent. Check battery.",1},
{"CBL0001",1,"Backplane <Bay ID> power cable disconnected.",0,0},
{"CBL0002",1,"Backplane <Bay ID> signal cable disconnected.",0,0},
{"CBL0003",1,"Backplane <Bay ID> <Connector Name> cable is disconnected.",0,0},
{"CBL0004",1,"The <Cable Name> cable is incorrectly connected to backplane <Bay ID> connector <Connector Name>.",0,0},
{"CBL0005",1,"Backplane <Bay ID> <Connector Name> connector incorrectly connected to the motherboard SATA controller.",0,0},
{"CBL0006",1,"Unsupported backplane <Bay ID> configuration: Multiple RAID controllers cannot be connected to the same backplane.",0,0},
{"CBL0007",1,"Backplane <Bay ID> <Cable Name> cable and backplane <Bay ID> <Cable Name> cable are swapped.",0,0},
{"CPU0000",3,"Internal error has occurred check for additional logs.",0,0},
{"CPU0001",1,"CPU <number> has a thermal trip (over-temperature) event.","CPU <number> has a thermal trip. Check CPU heat sink",4},
{"CPU0002",1,"CPU <number> has failed the built-in self-test (BIST).",0,0},
{"CPU0003",1,"CPU <number> is stuck in POST.",0,0},
{"CPU0004",1,"CPU <number> failed to initialize.",0,0},
{"CPU0005",1,"CPU <number> configuration is unsupported.","CPU <number> configuration is unsupported. Check CPU or BIOS revision",1},
{"CPU0006",1,"Unrecoverable CPU complex error detected on CPU <number>.",0,0},
{"CPU0007",3,"CPU <number> is present.",0,0},
{"CPU0008",2,"CPU <number> is disabled.",0,0},
{"CPU0009",3,"CPU <number> terminator is present.",0,0},
{"CPU0010",2,"CPU <number> is throttled.",0,0},
{"CPU0011",1,"Uncorrectable Machine Check Exception detected on CPU <number>.","Uncorrectable Machine Check Exception detected on CPU <number>. Contact Support",1},
{"CPU0012",2,"Correctable Machine Check Exception detected on CPU <number>.",0,0},
{"CPU0016",3,"CPU <number> is operating correctly.",0,0},
{"CPU0021",3,"CPU <number> is configured correctly.",0,0},
{"CPU0024",3,"CPU <number> is enabled.",0,0},
{"CPU0025",2,"CPU <number> terminator is absent.",0,0},
{"CPU0700",1,"CPU <number> initialization error detected.","CPU <number> initialization error detected. Power cycle system",1},
{"CPU0701",1,"CPU <number> protocol error detected.","CPU <number> protocol error detected. Power cycle system",1},
{"CPU0702",1,"CPU bus parity error detected.","CPU bus parity error detected. Power cycle system",1},
{"CPU0703",1,"CPU bus initialization error detected.","CPU bus initialization error detected.  Power cycle system",1},
{"CPU0704",1,"CPU <number> machine check error detected.","CPU <number> machine check error detected. Power cycle system",1},
{"CPU0800",3,"CPU <number> voltage regulator module is present.",0,0},
{"CPU0801",1,"CPU <number> voltage regulator module failed.","CPU <number> voltage regulator module failed. Reseat module",3},
{"CPU0802",2,"A predictive failure detected on CPU <number> voltage regulator module.",0,0},
{"CPU0803",1,"The power input for CPU <number> voltage regulator module is lost.","Lost power input for CPU <number> voltage regulator module. Reseat module",3},
{"CPU0804",1,"The power input for CPU <number> voltage regulator module is outside of range.","Power input for CPU <number> voltage regulator module is outside of range. Reseat module",3},
{"CPU0805",2,"The power input for CPU <number> voltage regulator module is outside of range, but it is attached to the system.",0,0},
{"CPU0806",1,"CPU <number> voltage regulator module is incorrectly configure.","CPU <number> voltage regulator module incorrectly configure. Check configuration",1},
{"CPU0816",1,"CPU <number> voltage regulator module is absent.","CPU <number> voltage regulator module absent. Check module",1},
{"CPU0817",3,"CPU <number> voltage regulator module is operating normally.",0,0},
{"CPU0819",3,"The power input for CPU <number> voltage regulator module has been restored.",0,0},
{"CPU0822",3,"CPU <number> voltage regulator module is configured correctly.",0,0},
{"CPU9000",3,"An OEM diagnostic event occurred.",0,0},
{"CPUA0023",1,"CPU <number> is absent","CPU <number> is absent.  Check CPU",1},
{"DKM1000",1,"A network problem detected. Cannot contact key management server.",0,0},
{"DKM1001",3,"The key management service is operating correctly.",0,0},
{"DKM1002",1,"Key management server certificate problem detected.",0,0},
{"DKM1004",1,"The key management server received a bad request.",0,0},
{"DKM1006",1,"Key management server error detected.","Key management server error.  Check configuration",1},
{"FAN0000",2,"Fan <number> RPM is less than the lower warning threshold.",0,0},
{"FAN0001",1,"Fan <number> RPM is less than the lower critical threshold.","Fan <number> RPM is outside of range. Check fan.",4},
{"FAN0002",2,"Fan <number> RPM is greater than the upper warning threshold.",0,0},
{"FAN0003",1,"Fan <number> RPM is greater than the upper critical threshold.","Fan <number> RPM is outside of range. Check fan.",4},
{"FAN0004",1,"Fan <number> RPM is outside of range.","Fan <number> RPM is outside of range. Check fan.",4},
{"FAN0005",3,"Fan <number> RPM is within range.",0,0},
{"FAN0006",1,"Fan <number> is removed.",0,0},
{"FAN0007",3,"Fan <number> was inserted.",0,0},
{"FAN0008",3,"Fan <number> is present.",0,0},
{"FAN0009",1,"Fan <number> is absent.","Fan <number> is absent.  Check Fan.",4},
{"FAN0010",2,"Fan <number> is disabled.",0,0},
{"FAN0011",3,"Fan <number> is enabled.",0,0},
{"FAN0012",2,"<name> RPM is less than the lower warning threshold.",0,0},
{"FAN0013",1,"<name> RPM is less than the lower critical threshold.",0,0},
{"FAN0014",2,"<name> RPM is greater than the upper warning threshold.",0,0},
{"FAN0015",1,"<name> RPM is greater than the upper critical threshold.",0,0},
{"FAN0016",1,"<name> RPM is outside of normal operating range.",0,0},
{"FAN0017",3,"<name> RPM is within normal operating range.",0,0},
{"FAN0018",2,"Enhanced Cooling Mode is not supported for fan <number>.",0,0},
{"FAN0019",3,"An incompatibility between operating mode and fan type was corrected for fan <number>.",0,0},
{"HWC1000",3,"The <name> is present.",0,0},
{"HWC1001",1,"The <name> is absent.","The <name> is absent. Check hardware",1},
{"HWC1002",3,"The <name> is disabled.",0,0},
{"HWC1003",3,"The <name> is enabled.",0,0},
{"HWC1004",3,"The storage adapter is present.",0,0},
{"HWC1005",1,"The storage adapter is absent.","The storage adapter is absent. Check hardware",1},
{"HWC1006",3,"The storage adapter is disabled.",0,0},
{"HWC1007",3,"The storage adapter is enabled.",0,0},
{"HWC1008",3,"The backplane is present.",0,0},
{"HWC1009",1,"The backplane is absent.","The backplane is absent. Check hardware",1},
{"HWC1010",3,"The backplane is disabled.",0,0},
{"HWC1011",3,"The backplane is enabled.",0,0},
{"HWC1012",3,"The USB cable is present.",0,0},
{"HWC1013",1,"The USB cable is absent.","The USB cable is absent.  Check cable",3},
{"HWC1014",3,"The mezzanine card <number> is present.",0,0},
{"HWC1015",1,"The mezzanine card <number> is absent.",0,0},
{"HWC1100",3,"The <name> was installed in slot <number>.",0,0},
{"HWC1101",3,"The <name> is removed from slot <number>.",0,0},
{"HWC1102",1,"The <name> is installed in an invalid slot <number>.",0,0},
{"HWC1103",3,"The <name> installed in the invalid slot <number> is removed.",0,0},
{"HWC1104",1,"The <name> installed in slot <number> is not supported.",0,0},
{"HWC1105",3,"The unsupported <name> in slot <number> is removed.",0,0},
{"HWC1200",3,"The sled <name> is inserted in slot <number>.",0,0},
{"HWC1201",1,"The sled <name> is removed from  slot <number>.",0,0},
{"HWC2000",3,"The <name> cable or interconnect is connected.",0,0},
{"HWC2001",1,"The <name> cable or interconnect is not connected or is improperly connected.","The <name> cable or interconnect failure.  Check connection",3},
{"HWC2002",3,"The storage <name> cable or interconnect is connected.",0,0},
{"HWC2003",1,"The storage <name> cable is not connected, or is improperly connected.","Storage <name> cable or interconnect failure.  Check connection",3},
{"HWC2004",3,"The system board <name> cable or interconnect is connected.",0,0},
{"HWC2005",1,"The system board <name> cable or interconnect is not connected, or is improperly connected.","System board <name> cable or interconnect failure.  Check connection",3},
{"HWC2006",1,"The <name> is not installed correctly.","<name> is not installed correctly. Check connection",1},
{"HWC2007",3,"The <name> is installed correctly.",0,0},
{"HWC2008",1,"A fabric mismatch detected for mezzanine card <number>.",0,0},
{"HWC2009",3,"Mezzanine card <number> is installed correctly.",0,0},
{"HWC2010",3,"The riser board cable or interconnect is connected.",0,0},
{"HWC2011",1,"The riser board cable or interconnect is not connected, or is improperly connected.","Riser board cable or interconnect failure.  Check connection",3},
{"HWC2012",1,"A fabric mismatch detected on fabric <name> with server in slot <number>.",0,0},
{"HWC2013",3,"Fabric mismatch corrected on fabric <name> with server in slot <number>.",0,0},
{"HWC2014",1,"A hardware misconfiguration detected on <name>.","A hardware misconfiguration detected on <name>. Check hardware",1},
{"HWC2015",3,"The <name> is configured correctly.",0,0},
{"HWC3000",1,"The <name> is removed.",0,0},
{"HWC3001",3,"The <name> is inserted.",0,0},
{"HWC3002",1,"Server <number> is removed.",0,0},
{"HWC3003",3,"Server <number> was inserted.",0,0},
{"HWC3004",1,"IO module <number> is removed.",0,0},
{"HWC3005",3,"IO module <number> was inserted.",0,0},
{"HWC3006",2,"Unable to QuickDeploy server in slot <number>.",0,0},
{"HWC4000",1,"A hardware incompatibility detected between BMC/iDRAC firmware and CPU.","Incompatibility between BMC/iDRAC firmware and CPU. Update firmware",1},
{"HWC4001",3,"A hardware incompatibility was corrected between BMC/iDRAC firmware and CPU.",0,0},
{"HWC4002",1,"A hardware incompatibility detected between BMC/iDRAC firmware and other hardware.",0,0},
{"HWC4003",3,"A hardware incompatibility was corrected between BMC/iDRAC firmware and other hardware.",0,0},
{"HWC4010",3,"Hardware successfully updated for mezzanine card <number>.",0,0},
{"HWC4011",1,"Hardware unsuccessfully updated for mezzanine card <number>.",0,0},
{"HWC4012",3,"Hardware successfully updated for embedded NIC.",0,0},
{"HWC4013",1,"Hardware unsuccessfully updated for embedded NIC.",0,0},
{"HWC4014",3,"Link Tuning data successfully updated.",0,0},
{"HWC4015",1,"Link Tuning error detected.",0,0},
{"HWC4016",1,"Hardware incompatibility detected with mezzanine card <number>.",0,0},
{"HWC4017",1,"A hardware incompatibility is detected between <name1><location1> and <name2><location2>.",0,0},
{"HWC4018",3,"A hardware incompatibility was corrected between <name1><location1> and <name2><location2>.",0,0},
{"HWC4019",1,"Unable to control the fan speed because a sled mismatch or hardware incompatibility is detected.","Unable to control the fan speed because a sled mismatch or hardware incompatibility is detected.",1},
{"HWC5000",3,"<name> is online.",0,0},
{"HWC5001",2,"<name> is offline.",0,0},
{"HWC5002",2,"A fabric mismatch detected on <name>.",0,0},
{"HWC5003",3,"<name> is operating correctly.",0,0},
{"HWC5004",2,"A link tuning failure detected on <name>.",0,0},
{"HWC5006",1,"A failure is detected on <name>.",0,0},
{"HWC5008",2,"Console is not available for the <name>.",0,0},
{"HWC5010",1,"<name> cannot detect any hosts.",0,0},
{"HWC5012",1,"On screen display (OSCAR) is not functional for the <name>.",0,0},
{"HWC5014",1,"<name> is not functional and is powered off.",0,0},
{"HWC5030",3,"IO module <number> is online.",0,0},
{"HWC5031",2,"IO module <number> is offline.",0,0},
{"HWC5032",2,"A fabric mismatch detected on IO module <number>.",0,0},
{"HWC5033",3,"IO module <number> is operating correctly.",0,0},
{"HWC5034",2,"A link tuning failure detected on IO module <number>.",0,0},
{"HWC5035",1,"An over-temperature event detected on I/O module <number>.",0,0},
{"HWC5036",1,"A failure is detected on IO module <number>.",0,0},
{"HWC5037",1,"I/O module <number> failed to boot.",0,0},
{"HWC5038",1,"Unable to turn on the I/O module <number>.",0,0},
{"HWC6000",2,"The <name> controller is offline.",0,0},
{"HWC6001",3,"The <name> controller is online.",0,0},
{"HWC6002",1,"The <name> controller is stuck in boot mode.",0,0},
{"HWC6003",3,"The <name> controller is booting.",0,0},
{"HWC6004",1,"Cannot communicate with <name> controller.",0,0},
{"HWC6005",3,"Communications restored for <name> controller.",0,0},
{"HWC7000",3,"Server <number> health changed to a normal state.",0,0},
{"HWC7002",2,"Server <number> health changed to a warning state from a normal state.",0,0},
{"HWC7004",1,"Server <number> health changed to a critical state from either a normal or warning state.",0,0},
{"HWC7006",1,"Server <number> health changed to a non-recoverable state from a less severe state.",0,0},
{"HWC7008",2,"Server <number> health changed to a warning state from more severe state.",0,0},
{"HWC7010",1,"Server <number> health changed to a critical state from a non-recoverable state.",0,0},
{"HWC7012",1,"Server <number> health changed to a non-recoverable state.",0,0},
{"HWC7014",1,"An invalid cable or incorrect cable configuration is detected.",0,0},
{"HWC9000",3,"The inlet temperature, fan health properties, and total power associated with the <name> device are restored to normal.",0,0},
{"HWC9001",2,"The <name> device may stop functioning because either the inlet temperature, fan health, or total power associated with the <name> device is reaching the threshold value.",0,0},
{"HWC9002",1,"The <name> device is not functioning because either the inlet temperature, fan health properties, or total power associated with the <name> device has exceeded the threshold values.",0,0},
{"HWC9003",2,"The <name> device is not functioning because of a Watchdog failure.",0,0},
{"LNK2700",1,"The <name> network link is down.",0,0},
{"LNK2701",3,"The <name> network link is up.",0,0},
{"MEM0000",3,"Persistent correctable memory errors detected on a memory device at location(s) <location>.",0,0},
{"MEM0001",1,"Multi-bit memory errors detected on a memory device at location(s) <location>.","Multi-bit memory error on <location>.  Reseat memory",5},
{"MEM0002",1,"Parity memory errors detected on a memory device at location <location>.",0,0},
{"MEM0003",1,"Stuck bit memory error detected on a memory device at location <location>.",0,0},
{"MEM0004",1,"Memory device at location <location> is disabled.",0,0},
{"MEM0005",1,"Persistent correctable memory error limit reached for a memory device at location(s) <location>.","Persistent correctable memory error limit reached for <location>. Reseat memory.",5},
{"MEM0006",3,"Memory device at location <location> is present.",0,0},
{"MEM0007",1,"Unsupported memory configuration; check memory device at location <location>.","Unsupported memory configuration. Check memory <location>.",5},
{"MEM0008",3,"Memory device at location <location> is spare memory.",0,0},
{"MEM0009",2,"Memory device at location <location> is throttled.",0,0},
{"MEM0010",1,"Memory device at location <location> is overheating.","Memory device <location> is over heating.  Check fans",4},
{"MEM0016",3,"Memory device at location(s) <location> is operating correctly.",0,0},
{"MEM0020",3,"Memory device at location <location> is enabled.",0,0},
{"MEM0021",3,"Persistent correctable memory error limit reset for a memory device at location <location>.",0,0},
{"MEM0022",2,"Memory device at location <location> is absent.",0,0},
{"MEM0024",3,"Memory device at location <location> is no longer spare memory.",0,0},
{"MEM0600",3,"Memory device was added at location <location>.",0,0},
{"MEM0601",3,"Memory device is removed from location <location>.",0,0},
{"MEM0700",3,"The persistent correctable memory error rate is at normal levels for a memory device at location <location>.",0,0},
{"MEM0701",2,"Correctable memory error rate exceeded for <location>.",0,0},
{"MEM0702",1,"Correctable memory error rate exceeded for <location>.","Correctable memory error rate exceeded for <location>. Reseat memory.",5},
{"MEM1000",3,"Memory device at location <location> transition to a running state.",0,0},
{"MEM1001",1,"Memory device at location <location> failed to transition to a running state.","Memory device <location> failed to transition to a running state. Reseat memory",5},
{"MEM1002",3,"Memory device at location <location> is in test.",0,0},
{"MEM1003",2,"Memory device at location <location> failed to transition to in test.",0,0},
{"MEM1004",3,"Memory device at location <location> is powered off.",0,0},
{"MEM1005",1,"Memory device at location <location> failed to power off.",0,0},
{"MEM1006",3,"Memory device at location <location> is online.",0,0},
{"MEM1007",1,"Memory device at location <location> failed to transition to online.",0,0},
{"MEM1008",3,"Memory device at location <location> is offline.",0,0},
{"MEM1009",1,"Memory device at location <location> failed to transition to offline.",0,0},
{"MEM1010",3,"Memory device at location <location> is off-duty.",0,0},
{"MEM1011",3,"Memory device at location <location> is on-duty.",0,0},
{"MEM1012",2,"Memory device at location <location> is in a degraded state.",0,0},
{"MEM1013",3,"Memory device at location <location> is in a full state.",0,0},
{"MEM1014",3,"Memory device at location <location> is in a power save state.",0,0},
{"MEM1015",3,"Memory device at location <location> is in a power active state.",0,0},
{"MEM1016",1,"Memory device at location <location> is not installed correctly.","Memory <location> is not installed correctly.  Re-install",5},
{"MEM1017",3,"Memory device at location <location> is installed correctly.",0,0},
{"MEM1200",3,"Memory RAID is redundant.",0,0},
{"MEM1201",1,"Memory RAID redundancy is lost. Check memory device at location(s) <location>.","Memory RAID lost on <location>. Power cycle system",5},
{"MEM1202",2,"Memory RAID redundancy is degraded. Check memory device at location(s) <location>.",0,0},
{"MEM1203",3,"Memory is not redundant.",0,0},
{"MEM1204",3,"Memory mirror is redundant.",0,0},
{"MEM1205",1,"Memory mirror redundancy is lost. Check memory device at location(s) <location>.","Memory mirror lost on <location>. Power cycle system",5},
{"MEM1206",2,"Memory mirror redundancy is degraded. Check memory device at location <location>.",0,0},
{"MEM1207",3,"Memory spare is redundant.",0,0},
{"MEM1208",1,"Memory spare redundancy is lost. Check memory device at location <location>.","Memory spared lost on <location>. Power cycle system",5},
{"MEM1209",3,"Memory spare redundancy is degraded. Check memory device at location <location>.",0,0},
{"MEM1210",3,"Memory is redundant.",0,0},
{"MEM1212",1,"Memory redundancy is lost.",0,0},
{"MEM1214",2,"Memory redundancy is degraded.",0,0},
{"MEM7000",3,"The memory riser mismatch was corrected.",0,0},
{"MEM7002",1,"A hardware mismatch detected for memory riser.","Memory riser mismatch detected. Check memory riser",5},
{"MEM8000",1,"Correctable memory error logging disabled for a memory device at location <location>.","SBE log disabled on <location>. Reseat memory",5},
{"MEM8001",3,"Persistent correctable memory error logging enabled for a memory device at location <location>.",0,0},
{"MEM9000",1,"Memory interconnect degraded.","Memory interconnect degraded. Reseat memory riser.",0},
{"MEM9001",3,"Memory interconnect is functioning normally.","Memory interconnect normal.",0},
{"MEM9002",2,"Intel QPI interconnect <number> has a correctable error.","Intel QPI interconnect <number> has a correctable error.",0},
{"MEM9003",2,"Intel SMI 2 Memory interconnect <number> has a correctable error.","Intel SMI 2 Memory interconnect <number> has a correctable error.",0},
{"MEM9004",1,"Intel QPI interconnect <number> has degraded.","Intel QPI interconnect <number> has degraded. Reseat processor.",0},
{"MEM9005",1,"Intel SMI 2 Memory interconnect <number> has degraded.","Intel SMI 2 interconnect <number> degraded. Reseat memory riser.",0},
{"MEM9006",1,"Intel QPI interconnect <number> has a non-recoverable issue.","Intel QPI interconnect <number> has fatal error. Reseat memory riser.",0},
{"MEM9007",1,"Intel SMI 2 Memory interconnect <number> has a non-recoverable issue.","Intel SMI 2 interconnect <number> has fatal error. Reseat mem riser.",0},
{"MEM9008",1,"Intel DDR Memory interconnect <number> has a non-recoverable issue.","Intel DDR interconnect <number> has fatal error. Reseat mem riser.",0},
{"MEM9009",2,"Intel DDR Memory interconnect <number> has a correctable error.","Intel DDR interconnect <number> has a correctable error. Reseat mem riser.",0},
{"MEM9010",3,"A QuickPath Interconnect (QPI) Reference Code warning message code is logged.",0,0},
{"MEM9011",2,"QuickPath Interconnect (QPI) Reference Code warning location information is logged.",0,0},
{"MEM9012",3,"A Memory Reference Code (MRC) warning code is logged.",0,0},
{"MEM9013",2,"Memory Reference Code (MRC) warning location information is logged.",0,0},
{"MEM9014",2,"A correctable memory error has occurred in Dual In-line Memory Module (DIMM) device <location>.",0,0},
{"MEM9015",1,"Multi-bit memory errors detected on a Dual In-line Memory Module (DIMM) device <location>.",0,0},
{"MEM9016",2,"Correctable memory error rate exceeded for Dual In-line Memory Module (DIMM)<location>.",0,0},
{"MEM9020",2,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> is about to reach the end of supported life duration.","The NVDIMM in <location> is approaching the end of supported life.",0},
{"MEM9030",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> is not responding and is disabled.","The NVDIMM in <location> not responding and has been disabled.",0},
{"MEM9031",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> is unable to save the data during the previous system shutdown operation or power loss.","The NVDIMM in <location> was not able to save its data and has been placed in write protect mode.",0},
{"MEM9032",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> is unable to restore the data that was saved in the previous 'save' operation.","The NVDIMM in <location> was not able to restore its data from its previous save operation and has been placed in write protect mode.",0},
{"MEM9033",1,"An unsupported Non-Volatile Dual In-line Memory Module (NVDIMM) device is of unsupported configuration and unable to operate as currently configured.","Illegal NVDIMM configuration detected.",0},
{"MEM9034",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> is not responding.","The NVDIMM in <location>is not responding",0},
{"MEM9035",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> cannot be configured to save data during a power loss because of an issue in the NVDIMM.","Unable to arm the NVDIMM in <location>.",0},
{"MEM9036",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) devices are placed in write-protect mode because the system may not provide sufficient power to save data in case of power loss.","All NVDIMMs are placed in Wrte Protect mode.",0},
{"MEM9037",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> has reached the end of supported life duration and is placed in write-protect mode.","Replace the NVDIMM.",0},
{"MEM9038",1,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> has lost persistency and is placed in write-protect mode.","Re-install the memory component. If the problem continues, contact support.",0},
{"MEM9050",3,"The Non-Volatile Dual In-line Memory Module (NVDIMM) device in the slot <location> has regained persistency and is available for use.",0,0},
{"OSD062",3,"The process of installing an operating system or hypervisor is started and is in progress.",0,1},
{"OSD063",3,"The process of installing an operating system or hypervisor is successfully completed.",0,1},
{"OSD064",3,"The process of installing an operating system or hypervisor is abruptly stopped either by the user or the installation infrastructure.",0,1},
{"OSD065",1,"Operating System/Hypervisor Installation did not complete successfully.",0,1},
{"OSE0000",3,"A critical stop occurred during OS load.",0,0},
{"OSE0001",3,"A runtime critical stop occurred.",0,0},
{"OSE0002",3,"An OS graceful stop occurred.",0,0},
{"OSE0003",3,"An OS graceful shut-down occurred.",0,0},
{"OSE0004",1,"A soft shut-down initiated by platform event filter.",0,0},
{"OSE0005",1,"Agent is not responding.",0,0},
{"OSE1000",3,"A: boot completed.",0,0},
{"OSE1001",1,"Failed to boot from A.",0,0},
{"OSE1002",3,"C: boot completed.",0,0},
{"OSE1003",1,"Failed to boot from C.",0,0},
{"OSE1004",3,"PXE boot completed.",0,0},
{"OSE1005",1,"PXE boot failed.",0,0},
{"OSE1006",3,"Diagnostic boot completed.",0,0},
{"OSE1007",1,"Diagnostic boot failed.",0,0},
{"OSE1008",3,"CD-ROM boot completed.",0,0},
{"OSE1009",1,"Failed to boot from CD-ROM.",0,0},
{"OSE1010",3,"ROM boot completed.",0,0},
{"OSE1011",1,"Failed to boot from ROM.",0,0},
{"OSE1012",3,"Boot completed.",0,0},
{"OSE1013",1,"Failed to boot.",0,0},
{"PCI1300",1,"A front panel diagnostic interrupt was detected.",0,0},
{"PCI1302",1,"A bus time-out was detected on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI1304",1,"An I/O channel check error was detected.","I/O channel check error detected. Power cycle system.",1},
{"PCI1306",1,"A software error was detected on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI1308",1,"A PCI parity error was detected on a component at bus <bus> device <device> function <func>.","PCI parity error on  bus <bus> device <device> function <func>. Power cycle system.",6},
{"PCI1310",1,"A PCI system error was detected on a component at bus <bus> device <device> function <func>.","PCI system error on bus <bus> device <device> function <func>. Power cycle system.",6},
{"PCI1312",1,"An EISA fail-safe time-out was detected.",0,0},
{"PCI1314",1,"A bus correctable error was detected on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI1316",1,"A bus uncorrectable error was detected on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI1318",1,"A fatal error was detected on a component at bus <bus> device <device> function <func>.","Fatal error on bus <bus> device <device> function <func>. Power cycle system.",6},
{"PCI1319",1,"A high-severity issue is detected in the SSD bay <bay>, Slot <number>.",0,1},
{"PCI1320",1,"A bus fatal error was detected on a component at bus <bus> device <device> function <func>.","Bus fatal error on bus <bus> device <device> function <func>. Power cycle system.",6},
{"PCI1321",1,"A high-severity issue is detected in a component of the bus <bus>, device 0, function <func>.",0,1},
{"PCI1322",2,"Bus performance degraded for a component at bus <bus> device <device> function <func>.",0,0},
{"PCI1342",1,"A bus time-out was detected on a component at slot <number>.",0,0},
{"PCI1344",1,"An I/O channel check error was detected.","An I/O channel check error detected. Power cycle system.",1},
{"PCI1346",1,"A software error was detected on a component at slot <number>.",0,0},
{"PCI1348",1,"A PCI parity error was detected on a component at slot <number>.","PCI parity error on slot <number>. Reseat PCI card",6},
{"PCI1350",1,"A PCI system error was detected on a component at slot <number>.","PCI system error on slot <number>. Reseat PCI card",6},
{"PCI1354",1,"A bus correctable error was detected on a component at slot <number>.",0,0},
{"PCI1356",1,"A bus uncorrectable error was detected on a component at slot <number>.",0,0},
{"PCI1358",1,"A fatal error was detected on a component at slot <number>.","Fatal error on slot <number>. Reseat PCI card",6},
{"PCI1360",1,"A bus fatal error was detected on a component at slot <number>.","Bus fatal error on slot <number>. Reseat PCI card",6},
{"PCI1362",2,"Bus performance degraded for a component at slot <number>.",0,0},
{"PCI2000",1,"A fatal IO error detected on a component at bus <bus> device <device> function <func>.","Fatal IO error on bus <bus> device <device> function <func>. Contact support",6},
{"PCI2001",3,"The component at bus <bus> device <device> function <func> recovered from a fatal IO error.",0,0},
{"PCI2002",1,"A fatal IO error detected on a component at slot <number>.","Fatal IO error on slot <number>. Contact support",6},
{"PCI2003",3,"The component at slot <number> recovered from a fatal IO error.",0,0},
{"PCI3000",1,"Device option ROM on embedded NIC failed to support Link Tuning or FlexAddress.",0,0},
{"PCI3001",3,"Device option ROM on embedded NIC was successfully updated.",0,0},
{"PCI3002",1,"Failed to program virtual MAC address on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI3003",3,"Virtual MAC address for component at bus <bus> device <device> function <func> was successfully programed.",0,0},
{"PCI3004",1,"Device option ROM on mezzanine card <number> failed to support Link Tuning or FlexAddress.",0,0},
{"PCI3005",3,"Device option ROM on mezzanine card <number> was successfully updated.",0,0},
{"PCI3006",1,"Failed to get Link Tuning or FlexAddress data from iDRAC.",0,0},
{"PCI3007",3,"Link Tuning or FlexAddress data successfully obtained.",0,0},
{"PCI3008",2,"A non-fatal PCIe error detected on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI3009",3,"PCIe is operating normally on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI3010",2,"A non-fatal IO error detected on a component at bus <bus> device <device> function <func>.",0,0},
{"PCI3011",3,"The component at bus <bus> device <device> function <func> recovered from a non-fatal IO error.",0,0},
{"PCI3012",2,"The QuickPath Interconnect (QPI) width degraded.",0,0},
{"PCI3013",3,"The QuickPath Interconnect (QPI) width regained.",0,0},
{"PCI3014",2,"A non-fatal PCIe error detected on a component at slot <number>.",0,0},
{"PCI3015",3,"The component at slot <number> recovered from a non-fatal PCIe error.",0,0},
{"PCI3016",1,"Device option ROM on mezzanine card failed to support Link Tuning or FlexAddress.",0,0},
{"PCI3017",3,"Device option ROM on mezzanine card was successfully updated.",0,0},
{"PCI3019",2,"A low-severity issue is detected in the SSD bay <bay>, Slot <number>.",0,0},
{"PCI3020",2,"A low-severity issue is detected in a component of the bus <bus>, device 0, function <func>.",0,0},
{"PDR1000",3,"Drive <number> is installed in disk drive bay <bay>.",0,0},
{"PDR1001",1,"Fault detected on drive <number> in disk drive bay <bay>.","Fault detected on drive <number> in disk drive bay <bay>. Check drive.",2},
{"PDR1002",2,"A predictive failure detected on drive <number> in disk drive bay <bay>.",0,0},
{"PDR1003",2,"Drive <number> in disk drive bay <bay> is the hot-spare drive.",0,0},
{"PDR1004",2,"Consistency check is in progress for drive <number> in disk drive bay <bay>.",0,0},
{"PDR1005",1,"Drive <number> in disk drive bay <bay> is in the critical array.","Drive <number> in disk drive bay <bay> is in the critical array. Replace drive.",2},
{"PDR1006",1,"Drive <number> in disk drive bay <bay> is in the failed array.","Drive <number> in disk drive bay <bay> is in the failed array. Replace drive.",2},
{"PDR1007",3,"Rebuild is in progress for drive <number> in disk drive bay <bay>.",0,0},
{"PDR1008",2,"Rebuild was aborted for drive <number> in disk drive bay <bay>.",0,0},
{"PDR1016",1,"Drive <number> is removed from disk drive bay <bay>.","Drive <number> removed from disk drive bay <bay>. Check drive.",2},
{"PDR1017",3,"Drive <number> in disk drive bay <bay> is operating normally.",0,0},
{"PDR1019",3,"Drive <number> in disk drive bay <bay> is no longer the hot-spare drive.",0,0},
{"PDR1020",3,"Consistency check for drive <number> in disk drive bay <bay> completed.",0,0},
{"PDR1021",3,"Drive <number> in disk drive bay <bay> is no longer in the critical array.",0,0},
{"PDR1022",3,"Drive <number> in disk drive bay <bay> is no longer in the failed array.",0,0},
{"PDR1023",3,"Rebuild completed for drive <number> in disk drive bay <bay>.",0,0},
{"PDR1024",1,"Drive mismatch detected for drive <number> in disk drive bay <bay>.","Drive mismatch detected for drive <number> in bay <bay>. Install correct drive type",2},
{"PDR1025",3,"Drive mismatch corrected for drive <number> in disk drive bay <bay>.",0,2},
{"PDR1100",3,"Drive <number> is installed.",0,0},
{"PDR1101",1,"Fault detected on drive <number>.","Fault detected on drive <number>. Check drive.",2},
{"PDR1102",2,"A predictive failure detected on drive <number>.",0,0},
{"PDR1103",2,"Drive <number> is the hot-spare drive.",0,0},
{"PDR1104",2,"Consistency check is in progress for drive <number>.",0,0},
{"PDR1105",1,"Drive <number> is in the critical array.","Drive <number> is in the critical array. Replace drive.",2},
{"PDR1106",1,"Drive <number> is in the failed array.","Drive <number> is in the failed array. Replace drive.",2},
{"PDR1107",3,"Rebuild is in progress for drive <number>.",0,0},
{"PDR1108",2,"Rebuild was aborted for drive <number>.",0,0},
{"PDR1116",1,"Drive <number> is removed.","Drive <number> is removed. Check drive",2},
{"PDR1117",3,"Drive <number> is operating normally.",0,0},
{"PDR1119",3,"Drive <number> is no longer the hot-spare drive.",0,0},
{"PDR1120",3,"Consistency check for drive <number> completed.",0,0},
{"PDR1121",3,"Drive <number> is no longer in the critical array.",0,0},
{"PDR1122",3,"Drive <number> is no longer in the failed array.",0,0},
{"PDR1123",3,"Rebuild completed for drive <number>.",0,0},
{"PFM0001",1,"The value of <name> is greater than the upper critical threshold.",0,0},
{"PFM0002",2,"The value of <name> is greater than the upper warning threshold.",0,0},
{"PFM0003",3,"The value of <name> is less than the lower warning threshold.",0,0},
{"PFM0004",3,"The value of <name> is within specified limits.",0,0},
{"PST0000",3,"Unrecognized Post Code.","Unrecognized Post Code.",0},
{"PST0001",3,"System Power On.","System Power On.",0},
{"PST0002",3,"CPU Microcode load.","CPU Microcode load.",0},
{"PST0003",3,"Chipset Initialization.","Started chipset initialization.",0},
{"PST0004",3,"Memory Configuration.","Memory configuration started.",0},
{"PST0005",3,"Shadow BIOS.","Shadow BIOS operation started.",0},
{"PST0006",3,"Multiprocessor Initialization.","Started multiprocessor initialization.",0},
{"PST0007",3,"POST processing start.","Started power on self test (POST).",0},
{"PST0008",3,"System Management Mode (SMM)initialization.","System Management Mode (SMM) initialization.",0},
{"PST0009",3,"PCI bus enumeration & video initialization.","PCI bus enumeration & video initialization.",0},
{"PST0010",3,"iDRAC is ready.","iDRAC initialization completed.",0},
{"PST0011",3,"Extended Memory test started.","Extended memory test started.",0},
{"PST0012",3,"Extended Memory test running \\","Extended Memory test running \\",0},
{"PST0013",3,"Extended Memory test running /","Extended Memory test running /",0},
{"PST0014",3,"Extended Memory test completed.","Extended Memory test completed.",0},
{"PST0064",3,"Display sign-on.","Display sign-on.",0},
{"PST0065",3,"PCI configuration.","PCI configuration.",0},
{"PST0080",2,"An issue was detected. System at boot F1/F2 prompt. Requires entry to continue.","System BIOS at F1/F2 prompt.",0},
{"PST0081",1,"No bootable devices.","No bootable devices found. Check bootable devices.",0},
{"PST0082",3,"In BIOS Setup Menu.","In BIOS Setup Menu.",0},
{"PST0083",3,"In BIOS Boot Menu.","In BIOS Boot Menu.",0},
{"PST0084",3,"Automated Task application.","Automated Task application.",0},
{"PST0085",3,"Performing CSIOR.","Performing CSIOR.",0},
{"PST0086",3,"In Lifecycle Controller.","In Lifecycle Controller.",0},
{"PST0087",3,"Initializing iDRAC.","Initializing iDRAC",0},
{"PST0088",3,"Preparing to Boot.","Preparing to Boot.",0},
{"PST0089",3,"A problem was detected during Power-On Self-Test (POST).",0,1},
{"PST0090",3,"A problem was detected related to the previous server boot.",0,1},
{"PST0091",3,"A problem was detected in Memory Reference Code (MRC).",0,1},
{"PST0126",3,"Giving control to UEFI aware OS.","Giving control to UEFI aware OS.",0},
{"PST0127",3,"Giving control to OS.","Giving control to OS.",0},
{"PST0128",1,"No memory is detected.","No memory is detected.  Inspect memory devices",5},
{"PST0129",1,"Memory is detected, but is not configurable.","Memory is detected, but is not configurable. Check memory devices",5},
{"PST0130",1,"Memory is configured, but not usable.","Memory is configured, but not usable.  Check memory devices",5},
{"PST0131",1,"System BIOS shadow failed.","System BIOS shadow failed. Check memory devices",5},
{"PST0132",1,"CMOS failed.","CMOS failed. Power cycle system",1},
{"PST0133",1,"DMA controller failed.","DMA controller failed.  Power cycle system",1},
{"PST0134",1,"Interrupt controller failed.","Interrupt controller failed.  Power cycle system",1},
{"PST0135",1,"Timer refresh failed.","Timer refresh failed.  Power cycle system",1},
{"PST0136",1,"Programmable interval timer error.","Programmable interval timer error. Power cycle system",1},
{"PST0137",1,"Parity error.","Parity error.  Power cycle system",1},
{"PST0138",1,"SuperIO failed.","SuperIO failure. Power cycle system",1},
{"PST0139",1,"Keyboard controller failed.","Keyboard controller failed.  Power cycle system",1},
{"PST0140",1,"System management interrupt initialization failed.","SMI initialization failed. Power cycle system",1},
{"PST0141",1,"QuickPath Interconnect (QPI) fatal error.","QuickPath Interconnect (QPI) fatal error.  Contact support",1},
{"PST0142",1,"MRC fatal error.","Memory initialization error. Contact support",5},
{"PST0143",1,"Intel Trusted Execution Technology (TXT) fatal error.","Intel Trusted Execution Technology (TXT) fatal error. Contact support",1},
{"PST0144",1,"Unable to load required BIOS files.","Unable to load required BIOS files.",0},
{"PST0192",1,"Shut-down test failed.","Shut-down test failed. Power cycle system",1},
{"PST0193",1,"BIOS POST memory test failed.","BIOS POST memory test failed.   Check memory devices",5},
{"PST0194",1,"Remote access controller configuration failed.","Remote access controller configuration failed.   Check screen message",1},
{"PST0195",1,"CPU configuration failed.","CPU configuration failed. Check screen message",1},
{"PST0196",1,"Incorrect memory configuration.","Incorrect memory configuration.  Review User Guide",5},
{"PST0208",1,"System BIOS has halted.","System BIOS has halted. Check console for details.",0},
{"PST0209",1,"System BIOS has halted due to Non-Maskable Interrupt (NMI).","System halted due to NMI: Check Console for Details",0},
{"PST0254",1,"General failure after video.","General failure after video.  Check screen message",1},
{"PST0256",1,"POST fatal error detected.","POST fatal error detected. Contact support",1},
{"PSU0000",3,"Power supply <number> is present.",0,0},
{"PSU0001",1,"Power supply <number> failed.","PSU <number> failed. Check PSU",3},
{"PSU0002",2,"A predictive failure detected on power supply <number>.","Predictive failure on PSU <number>. Check PSU",3},
{"PSU0003",1,"The power input for power supply <number> is lost.","Power input for PSU <number> is lost. Check PSU cables",3},
{"PSU0004",1,"The power input for power supply <number> is outside of range.","Power input for PSU <number> is outside of range. Check PSU cables",3},
{"PSU0005",2,"The power input for power supply <number> is outside of the allowable range, but it is attached to the system.",0,0},
{"PSU0006",1,"Power supply <number> is incorrectly configured.","Power supply <number> is incorrectly configured. Check PSU.",3},
{"PSU0007",2,"Power supply <number> is operating at 110 volts, and could cause a circuit breaker fault.",0,0},
{"PSU0017",3,"Power supply <number> is operating normally.",0,0},
{"PSU0019",3,"The input power for power supply <number> has been restored.",0,0},
{"PSU0022",3,"Power supply <number> is correctly configured.",0,0},
{"PSU0023",3,"Power supply <number> operating at 110 volts has been acknowledged by user.",0,0},
{"PSU0031",1,"Cannot communicate with power supply <number>.","Cannot communicate with PSU <number>. Reseat PSU.",3},
{"PSU0032",2,"The temperature for power supply <number> is in a warning range.",0,0},
{"PSU0033",1,"The temperature for power supply <number> is outside of range.","PSU <number> temperature outside of range. Check PSU",4},
{"PSU0034",1,"An under voltage fault detected on power supply <number>.","An under voltage fault detected on PSU <number>. Check power source.",3},
{"PSU0035",1,"An over voltage fault detected on power supply <number>.","Over voltage fault on PSU <number>. Check PSU",3},
{"PSU0036",1,"An over current fault detected on power supply <number>.","An over current fault detected on PSU <number>.  Check PSU.",3},
{"PSU0037",1,"Fan failure detected on power supply <number>.","Fan failure detected on PSU <number>.  Check PSU.",3},
{"PSU0038",3,"Power supply <number> fan is operating normally.",0,0},
{"PSU0039",1,"An under current fault detected on power supply <number>.","Under current fault detected on PSU <number>.  Check PSU.",3},
{"PSU0040",1,"An output under voltage fault detected on power supply <number>.","Output under voltage fault detected on PSU <number>.",3},
{"PSU0041",1,"An output over voltage fault detected on power supply <number>.","Output over voltage fault on PSU <number>. Check PSU",3},
{"PSU0042",1,"An output over current fault detected on power supply <number>.","Output over current fault detected on PSU <number>.  Check PSU.",3},
{"PSU0043",1,"An output under current fault detected on power supply <number>.","Output under current fault detected on PSU <number>.  Check PSU.",3},
{"PSU0044",2,"Cannot obtain status information from power supply <number>.",0,0},
{"PSU0045",3,"Power supply <number> status information successfully obtained.",0,0},
{"PSU0046",3,"Communication has been restored to power supply <number>.",0,0},
{"PSU0076",1,"A power supply wattage mismatch is detected; power supply <number> is rated for <value> watts.","PSU wattage mismatch; PSU <number> = <value> watts",3},
{"PSU0077",1,"Power supply <number> vendor type mismatch detected.",0,0},
{"PSU0078",1,"Power supply <number> revision mismatch detected.",0,0},
{"PSU0080",1,"Power supply <number> voltage rating does not match the system's requirements.",0,0},
{"PSU0090",3,"Power supply <number> wattage mismatch corrected.",0,0},
{"PSU0091",2,"Power supply unit <number> rating exceeds the system power distribution limits.","Power supply <number> exceeds power distribution limits. Remove PSU.",0},
{"PSU0092",3,"Power supply unit <number> rating is appropriate for the system power distribution limits.",0,0},
{"PSU0900",3,"Power unit <number> is off.",0,0},
{"PSU0901",3,"Power unit <number> is on.",0,0},
{"PSU0902",3,"Power unit <number> was power cycled.",0,0},
{"PSU0904",1,"Could not power down 240VA on power unit <number>.",0,0},
{"PSU0906",1,"An interlock power down error detected on power unit <number>.",0,0},
{"PSU0907",3,"An interlock power down error was corrected for power unit <number>.",0,0},
{"PSU0908",1,"Power lost on power unit <number>.",0,0},
{"PSU0909",3,"Power restored on power unit <number>.",0,0},
{"PSU0910",1,"Soft power control failure detected on power unit <number>.",0,0},
{"PSU0911",3,"Soft power control restored on power unit <number>.",0,0},
{"PSU0912",1,"A failure detected on power unit <number>.",0,0},
{"PSU0913",3,"Power unit <number> is operating normally.",0,0},
{"PSU0914",2,"A predictive failure detected on power unit <number>.",0,0},
{"PSUA0016",1,"Power supply <number> is absent.","PSU <number> is absent. Check PSU",3},
{"PWR0100",3,"The power button was pressed.",0,0},
{"PWR0101",3,"The power button was released.",0,0},
{"PWR0102",3,"The sleep button was pressed.",0,0},
{"PWR0103",3,"The sleep button was released.",0,0},
{"PWR0104",3,"The reset button was pressed.",0,0},
{"PWR0105",3,"The reset button was released.",0,0},
{"PWR0106",3,"The <name> is latched.",0,0},
{"PWR0107",3,"The <name> is unlatched.",0,0},
{"PWR0108",3,"The <name> service was requested.",0,0},
{"PWR0109",3,"The <name> service has completed.",0,0},
{"PWR1000",3,"The system performance restored.",0,0},
{"PWR1001",2,"The system performance degraded.","System performance degraded. Check PSUs and system configuration",3},
{"PWR1002",2,"The system performance degraded because of thermal protection.",0,0},
{"PWR1003",2,"The system performance degraded because cooling capacity has changed.",0,0},
{"PWR1004",2,"The system performance degraded because power capacity has changed.",0,0},
{"PWR1005",2,"The system performance degraded because of user-defined power capacity has changed.",0,0},
{"PWR1006",1,"The system halted because system power exceeds capacity.","System power exceeds capacity. System halted. Contact support",3},
{"PWR1007",2,"The system performance degraded because power exceeds capacity.","System power exceeds capacity. Performance degraded.  Check PSU configuration",3},
{"PWR1008",1,"The system performance degraded because power draw exceeds the power threshold.","System power exceeds threshold. Performance degraded.  Check PSU configuration",3},
{"PWR1009",3,"System power capacity is restored.",0,0},
{"PWR2000",3,"The system powered up.",0,0},
{"PWR2001",3,"The system hard reset.",0,0},
{"PWR2002",3,"The system warm reset.",0,0},
{"PWR2003",3,"User requested a PXE boot.",0,0},
{"PWR2004",3,"System booted automatically into diagnostics.",0,0},
{"PWR2005",3,"The OS run-time software initiated a hard reset.",0,0},
{"PWR2006",3,"The OS run-time software initiated a warm reset.",0,0},
{"PWR2007",3,"System restarted.",0,0},
{"PWR2200",3,"The system is in the ON state.",0,0},
{"PWR2201",3,"The system is sleeping with system hardware and processor context maintained.",0,0},
{"PWR2202",3,"The system is sleeping with lost processor context.",0,0},
{"PWR2203",3,"The system is sleeping with system hardware and processor context lost.",0,0},
{"PWR2204",3,"The system is in a non-volatile sleep state.",0,0},
{"PWR2205",3,"The system is in a soft-off state.",0,0},
{"PWR2207",3,"The system is in a mechanical off state.",0,0},
{"PWR2208",3,"The system is in a sleep state.",0,0},
{"PWR2209",3,"The system is in an undermined sleep state.",0,0},
{"PWR2210",3,"The system was forced into a soft-off state.",0,0},
{"PWR2211",3,"The system is in legacy ON state.",0,0},
{"PWR2212",3,"The system is in legacy OFF state.",0,0},
{"RDU0001",3,"The fans are redundant.",0,0},
{"RDU0002",1,"Fan redundancy is lost.","Fan redundancy is lost. Check fans.",4},
{"RDU0003",2,"Fan redundancy is degraded.",0,0},
{"RDU0004",3,"The fans are not redundant.",0,0},
{"RDU0005",1,"The fans are not redundant. Insufficient resources to maintain normal operations.",0,0},
{"RDU0011",3,"The power supplies are redundant.",0,0},
{"RDU0012",1,"Power supply redundancy is lost.","Lost PSU redundancy. Check PSU cables",3},
{"RDU0013",2,"Power supply redundancy is degraded.","PSU redundancy degraded. Check PSU cables",3},
{"RDU0014",3,"The power supplies are not redundant.",0,0},
{"RDU0015",1,"The power supplies are not redundant. Insufficient resources to maintain normal operations.","PSUs are not redundant. Insufficient resources. Check PSU cables.",3},
{"RDU0016",3,"The storage voltage is redundant.",0,0},
{"RDU0017",2,"The storage power redundancy is no longer available.",0,0},
{"RDU0018",2,"The storage power redundancy is degraded.",0,0},
{"RDU0019",3,"The storage voltage is not redundant.",0,0},
{"RDU0030",3,"The <name> voltage is redundant.",0,0},
{"RDU0031",1,"The <name> voltage redundancy is lost.",0,0},
{"RDU0032",2,"The <name> voltage redundancy is degraded.",0,0},
{"RDU0033",3,"The <name> voltage is not redundant.",0,0},
{"RFL2000",3,"Internal Dual SD Module <name> is present.",0,0},
{"RFL2002",2,"Internal Dual SD Module <name> is offline.",0,0},
{"RFL2003",3,"Internal Dual SD Module <name> is online.",0,0},
{"RFL2004",1,"Failure detected on Internal Dual SD Module <name>.","Internal Dual SD Module <name> failed.  Check SD Card",1},
{"RFL2005",3,"Internal Dual SD Module <name> is operating normally.",0,0},
{"RFL2006",2,"Internal Dual SD Module <name> is write protected.","Internal Dual SD Module <name> is write protected.  Check SD Card",1},
{"RFL2007",3,"Internal Dual SD Module <name> is writable.",0,0},
{"RFL2008",3,"Internal Dual SD Module <name> is disabled.",0,0},
{"RFL2009",3,"Internal Dual SD Module <name> is enabled.",0,0},
{"RFLA2001",1,"Internal Dual SD Module <name> is absent.","Internal Dual SD Module <name> is absent.  Check SD card.",1},
{"RFM1018",3,"Removable Flash Media is absent.",0,0},
{"RFM1019",3,"Removable Flash Media is present.",0,0},
{"RFM1020",3,"Removable Flash Media is IPMI-function ready.",0,0},
{"RFM1021",2,"Removable Flash Media is not IPMI-function ready.",0,0},
{"RFM1022",3,"Removable Flash Media is ready.",0,0},
{"RFM1023",2,"Removable Flash Media is not ready.",0,0},
{"RFM1024",2,"Removable Flash Media is offline.",0,0},
{"RFM1025",3,"Removable Flash Media is online.",0,0},
{"RFM1026",1,"Failure detected on Removable Flash Media.",0,0},
{"RFM1027",3,"Removable Flash Media is operating normally.",0,0},
{"RFM1028",3,"Removable Flash Media was activated.",0,0},
{"RFM1029",3,"Removable Flash Media was deactivated.",0,0},
{"RFM1030",3,"Removable Flash Media is booting.",0,0},
{"RFM1031",3,"Removable Flash Media has finished booting.",0,0},
{"RFM1032",2,"Removable Flash Media is write protected.",0,0},
{"RFM1033",3,"Removable Flash Media is writable.",0,0},
{"RFM1034",1,"Media not present for Removable Flash Media.",0,0},
{"RFM1035",3,"Media is present for Removable Flash Media.",0,0},
{"RRDU0001",3,"Internal Dual SD Module is redundant.",0,0},
{"RRDU0002",1,"Internal Dual SD Module redundancy is lost.","Internal Dual SD Module redundancy lost. Check SD cards",1},
{"RRDU0003",2,"Internal Dual SD Module redundancy is degraded.",0,0},
{"RRDU0004",3,"Internal Dual SD Module is not redundant.",0,0},
{"RRDU0005",1,"Internal Dual SD Module is not redundant. Insufficient resources to maintain normal operations.","Internal Dual SD Module is not redundant. Insufficient resources. Check SD Cards",1},
{"SEC0000",1,"The chassis is open.","Intrusion detected. Check chassis cover",1},
{"SEC0001",1,"The drive bay is open.",0,0},
{"SEC0002",1,"The I/O card area is open.",0,0},
{"SEC0003",1,"The processor area is open.",0,0},
{"SEC0004",1,"The LAN is disconnected.",0,0},
{"SEC0005",1,"Unauthorized docking is detected.",0,0},
{"SEC0006",1,"The fan area is open.",0,0},
{"SEC0016",3,"The chassis is closed.",0,0},
{"SEC0017",3,"The drive bay is closed.",0,0},
{"SEC0018",3,"The I/O card area is closed.",0,0},
{"SEC0019",3,"The processor area is closed.",0,0},
{"SEC0020",3,"The LAN is connected.",0,0},
{"SEC0021",3,"The docking is authorized.",0,0},
{"SEC0022",3,"The fan area is closed.",0,0},
{"SEC0031",1,"The chassis is open while the power is on.","Intrusion detected. Check chassis cover",1},
{"SEC0032",3,"The chassis is closed while the power is on.",0,0},
{"SEC0033",1,"The chassis is open while the power is off.","Intrusion detected. Check chassis cover",1},
{"SEC0034",3,"The chassis is closed while the power is off.",0,0},
{"SEC0040",1,"A critical stop occurred during OS load.",0,0},
{"SEC0041",1,"BIOS is unable to configure the Intel Trusted Execution Technology (TXT).","Unable to configure TXT. Reconfigure TPM and TXT in BIOS.",1},
{"SEC0042",1,"Processor detected a problem while performing an Intel Trusted Execution Technology (TXT) operation.","Problem with TXT operation.  Reconfigure TPM and TXT in BIOS.",1},
{"SEC0043",1,"BIOS Authenticated Code Module detected an Intel Trusted Execution Technology (TXT) problem during POST.","TXT problem during POST. Reconfigure TPM and TXT in BIOS.",1},
{"SEC0044",1,"SINIT Authenticated Code Module detected an Intel Trusted Execution Technology (TXT) problem at boot.","TXT problem at boot. Reconfigure TPM and TXT in BIOS.",1},
{"SEC0045",3,"Intel Trusted Execution Technology (TXT) is operating correctly.",0,0},
{"SEC0100",2,"The <name> in slot <number> is open.",0,0},
{"SEC0101",1,"The <name> in slot <number> is opened for more than 3 minutes.",0,0},
{"SEC0102",3,"The <name> in slot <number> is closed.",0,0},
{"SEC0600",2,"A secure mode violation detected.",0,0},
{"SEC0601",3,"A secure mode violation was corrected.",0,0},
{"SEC0602",2,"User password violation detected.",0,0},
{"SEC0603",3,"User password violation was corrected.",0,0},
{"SEC0604",1,"A setup password violation detected.",0,0},
{"SEC0605",3,"A setup password violation was corrected.",0,0},
{"SEC0606",2,"The network boot password violation detected.",0,0},
{"SEC0607",3,"The network boot password violation was corrected.",0,0},
{"SEC0608",2,"A password violation detected.",0,0},
{"SEC0609",3,"A password violation was corrected.",0,0},
{"SEC0610",2,"An Out-of-band password violation detected.",0,0},
{"SEC0611",3,"An Out-of-band password violation was corrected.",0,0},
{"SEC0612",2,"The default username and password is currently in use. It is recommended to immediately change the default credentials.",0,0},
{"SEC0613",3,"The default username and password is changed.",0,0},
{"SEL0002",1,"Logging is disabled.",0,0},
{"SEL0003",3,"Logging is enabled.",0,0},
{"SEL0004",3,"Log cleared.",0,0},
{"SEL0006",1,"All event logging is disabled.",0,0},
{"SEL0007",3,"All event logging is enabled.",0,0},
{"SEL0008",1,"System event log (SEL) is full.","SEL is full.  Review & clear log",1},
{"SEL0010",2,"System event log (SEL) is almost full.",0,0},
{"SEL0012",1,"Could not create or initialize the system event log.",0,0},
{"SEL0013",3,"The system event log was created or initialized successfully.",0,0},
{"SEL1200",3,"The system was reconfigured.",0,0},
{"SEL1202",3,"OEM system boot.",0,0},
{"SEL1204",1,"An unknown system hardware failure detected.","Unknown system hardware failure. Contact support",1},
{"SEL1205",3,"The unknown system hardware failure was corrected.",0,0},
{"SEL1206",3,"An entry was added to auxiliary log.",0,0},
{"SEL1207",3,"An entry was removed from auxiliary log.",0,0},
{"SEL1208",3,"A platform event filter action was executed.",0,0},
{"SEL1209",1,"The platform event filter action failed.",0,0},
{"SEL1210",3,"The time-stamp clock is synchronized.",0,0},
{"SEL1211",1,"The time-stamp clock could not be synchronized.",0,0},
{"SEL1300",1,"No bootable media found.",0,0},
{"SEL1301",3,"Bootable media found.",0,0},
{"SEL1302",1,"Non-bootable diskette detected.",0,0},
{"SEL1303",3,"Bootable diskette detected.",0,0},
{"SEL1304",1,"The PXE server not found.",0,0},
{"SEL1305",3,"The PXE server found.",0,0},
{"SEL1306",1,"Invalid boot sector found.",0,0},
{"SEL1307",3,"Boot sector found.",0,0},
{"SEL1308",1,"A time-out occurred while waiting for user to select a boot source.",0,0},
{"SEL1309",3,"User selected a boot source.",0,0},
{"SEL1400",3,"The platform generated a page alert.",0,0},
{"SEL1402",3,"The platform generated a LAN alert.",0,0},
{"SEL1404",3,"A platform event trap (PET) was generated.",0,0},
{"SEL1406",3,"The platform generated a SNMP trap.",0,0},
{"SEL1500",3,"The chassis management controller (CMC) is redundant.",0,0},
{"SEL1501",1,"Chassis management controller (CMC) redundancy is lost.",0,0},
{"SEL1502",2,"Chassis management controller (CMC) redundancy is degraded.",0,0},
{"SEL1503",3,"The chassis management controller (CMC) is not redundant.",0,0},
{"SEL1504",1,"The chassis management controller (CMC) is not redundant. Insufficient resources to maintain normal operations.",0,0},
{"SEL1506",2,"Lost communications with Chassis Group Member <number>.",0,0},
{"SEL1507",3,"Communications restored with Chassis Group Member <number>.",0,0},
{"SEL1508",2,"Member <number> could not join the Chassis Group.",0,0},
{"SEL1509",3,"Member <number> has joined the Chassis Group.",0,0},
{"SEL1510",2,"An authentication error detected for Chassis Group Member <number>.",0,0},
{"SEL1511",3,"Member <number> removed from the Chassis Group.",0,0},
{"SEL1512",1,"The Chassis Controller is not responding or is not inserted properly. The status of Chassis Controller is critical.",0,0},
{"SEL1513",3,"The status of Chassis Controller has changed from critical to OK.",0,0},
{"SEL1514",1,"The Inlet Temp Sensor is not responding or is not working properly. The status of Sensor health is critical.",0,0},
{"SEL1515",1,"One of the I2C sensor is not responding or is not working properly. The status of Sensor health  is critical.",0,0},
{"SEL9900",3,"An unsupported event occurred.",0,0},
{"SEL9901",3,"OEM software event.",0,0},
{"SEL9902",3,"System software event.",0,0},
{"SWC4004",2,"A firmware or software incompatibility detected between iDRAC in slot <number> and CMC.",0,0},
{"SWC4005",3,"A firmware or software incompatibility was corrected between iDRAC in slot <number> and CMC.",0,0},
{"SWC4006",2,"A firmware or software incompatibility detected between system BIOS in slot <number> and CMC.",0,0},
{"SWC4007",3,"A firmware or software incompatibility was corrected between system BIOS in slot <number> and CMC.",0,0},
{"SWC4008",2,"A firmware or software incompatibility detected between CMC 1 and CMC 2.",0,0},
{"SWC4009",3,"A firmware or software incompatibility was corrected between CMC 1 and CMC 2.",0,0},
{"SWC4010",2,"<name><location1> in Server-<location2> requires a version of Chassis Management Controller (CMC) firmware 5.0 or later for using the NParEP (ARI mode) functions.",0,0},
{"SWC4011",3,"A firmware or software incompatibility is automatically corrected between the <name><location1> in Server-<location2> and the Chassis Management Controller (CMC).",0,0},
{"SWC4012",1,"A firmware or software incompatibility is detected between <name1><location1> and <name2><location2>.",0,0},
{"SWC4013",3,"A firmware or software incompatibility was corrected between <name1><location1> and <name2><location2>.",0,0},
{"SWC5000",3,"<name> upgrade was successful.",0,0},
{"SWC5001",1,"<name> upgrade failed.",0,0},
{"SWC5002",2,"<name> upgrade was successful but encountered minor errors.",0,0},
{"SWC5003",2,"System Controller (SC) has either stopped functioning or is updating a firmware version.",0,0},
{"SWC5004",3,"System Controller (SC) has restarted functioning.",0,0},
{"SWC5005",1,"Unable to update the System Controller (SC) firmware",0,0},
{"SWC5006",3,"System Controller (SC) Firmware Update Successful",0,0},
{"SWC5007",2,"Unable to access the System Controller (SC) because of a degraded functionality.",0,0},
{"SWC5008",1,"Unable to access the System Controller (SC) because of a hardware error condition.",0,0},
{"TMP0100",2,"The system board <name> temperature is less than the lower warning threshold.",0,0},
{"TMP0101",1,"The system board <name> temperature is less than the lower critical threshold.","System board temperature is outside of range.  Check Fans",4},
{"TMP0102",2,"The system board <name> temperature is greater than the upper warning threshold.",0,0},
{"TMP0103",1,"The system board <name> temperature is greater than the upper critical threshold.","System board temperature is outside of range.  Check Fans",4},
{"TMP0104",1,"The system board <name> temperature is outside of range.","System board <name> temperature is outside of range  Check Fans",4},
{"TMP0105",3,"The system board <name> temperature is within range.",0,0},
{"TMP0106",2,"The memory module <number> temperature is less than the lower warning threshold.",0,0},
{"TMP0107",1,"The memory module <number> temperature is less than the lower critical threshold.","Memory module <number> temperature  is outside of range.  Check Fans",4},
{"TMP0108",2,"The memory module <number> temperature is greater than the upper warning threshold.",0,0},
{"TMP0109",1,"The memory module <number> temperature is greater than the upper critical threshold.","Memory module <number> temperature  is outside of range.  Check Fans",4},
{"TMP0110",1,"The memory module <number> temperature is outside of range.","Memory module <number> temperature  is outside of range.  Check Fans",4},
{"TMP0111",3,"The memory module <number> temperature is within range.",0,0},
{"TMP0112",2,"The <name> temperature is less than the lower warning threshold.",0,0},
{"TMP0113",1,"The <name> temperature is less than the lower critical threshold.","The <name> temperature is outside of range. Check Fans",4},
{"TMP0114",2,"The <name> temperature is greater than the upper warning threshold.",0,0},
{"TMP0115",1,"The <name> temperature is greater than the upper critical threshold.","The <name> temperature is outside of range  .  Check Fans",4},
{"TMP0116",1,"The <name> temperature is outside of range.","The <name> temperature  is outside of range.  Check Fans",4},
{"TMP0117",3,"The <name> temperature is within range.",0,0},
{"TMP0118",2,"The system inlet temperature is less than the lower warning threshold.","Inlet temperature is lower than warning threshold. Check environment.",0},
{"TMP0119",1,"The system inlet temperature is less than the lower critical threshold.","Inlet temperature is lower than critical threshold. Check environment",4},
{"TMP0120",2,"The system inlet temperature is greater than the upper warning threshold.","Inlet temperature is greater than upper warning threshold. Check environment.",0},
{"TMP0121",1,"The system inlet temperature is greater than the upper critical threshold.","Inlet temperature is greater than upper critical threshold. Check environment",4},
{"TMP0122",1,"The system inlet temperature is outside of range.","Inlet temperature is outside of range . Check environment",4},
{"TMP0123",3,"The system inlet temperature is within range.",0,0},
{"TMP0124",2,"Disk drive bay temperature is less than the lower warning threshold.",0,0},
{"TMP0125",1,"Disk drive bay temperature is less than the lower critical threshold.",0,0},
{"TMP0126",2,"Disk drive bay temperature is greater than the upper warning threshold.",0,0},
{"TMP0127",1,"Disk drive bay temperature is greater than the upper critical threshold.",0,0},
{"TMP0128",1,"Disk drive bay temperature is outside of  range.",0,0},
{"TMP0129",3,"Disk drive bay temperature is within range.",0,0},
{"TMP0130",2,"The control panel temperature is less than the lower warning threshold.",0,0},
{"TMP0131",1,"The control panel temperature is less than the lower critical threshold.",0,0},
{"TMP0132",2,"The control panel temperature is greater than the upper warning threshold.",0,0},
{"TMP0133",1,"The control panel temperature is greater than the upper critical threshold.",0,0},
{"TMP0134",1,"The control panel temperature is outside of range.",0,0},
{"TMP0135",3,"The control panel temperature is within range.",0,0},
{"TMP0136",1,"The system is automatically turned off because of insufficient cooling.","Insufficient system cooling detected. Check fans",4},
{"TMP0137",3,"The system cooling is working normally.",0,0},
{"TMP0138",3,"The C1 Enhance (C1E) state is disabled in the server. Increased fan speeds can be expected during high CPU workload.",0,0},
{"TMP0200",2,"CPU <number> temperature is less than the lower warning threshold.",0,0},
{"TMP0201",1,"CPU <number> temperature is less than the lower critical threshold.","CPU <number> temperature is outside of range. Check fans",4},
{"TMP0202",2,"CPU <number> temperature is greater than the upper warning threshold.",0,0},
{"TMP0203",1,"CPU <number> temperature is greater than the upper critical threshold.","CPU <number> temperature is outside of range. Check fans",4},
{"TMP0204",1,"CPU <number> temperature is outside of range.","CPU <number> temperature is outside of range. Check fans",4},
{"TMP0205",3,"CPU <number> temperature is within range.",0,0},
{"TMP0300",3,"The Enhanced Cooling Mode feature is enabled.",0,0},
{"TMP0301",3,"The Enhanced Cooling Mode feature is disabled.",0,0},
{"TMP0302",2,"Unable to set Enhanced Cooling Mode because the required power or fan configuration is not available.",0,0},
{"VFL1001",3,"Removable Flash Media <name> is present.",0,0},
{"VFL1002",3,"Removable Flash Media <name> is IPMI-function ready.",0,0},
{"VFL1003",2,"Removable Flash Media <name> is not IPMI-function ready.",0,0},
{"VFL1004",3,"Removable Flash Media <name> is ready.",0,0},
{"VFL1005",2,"Removable Flash Media <name> is not ready.",0,0},
{"VFL1006",2,"Removable Flash Media <name> is offline.",0,0},
{"VFL1007",3,"Removable Flash Media <name> is online.",0,0},
{"VFL1008",1,"Failure detected on Removable Flash Media <name>.","Removable Flash Media <name> failed.  Check SD Card",1},
{"VFL1009",3,"Removable Flash Media <name> is operating normally.",0,0},
{"VFL1010",3,"Removable Flash Media <name> was activated.",0,0},
{"VFL1011",3,"Removable Flash Media <name> was deactivated.",0,0},
{"VFL1012",3,"Removable Flash Media <name> is booting.",0,0},
{"VFL1013",3,"Removable Flash Media <name> has finished booting.",0,0},
{"VFL1014",2,"Removable Flash Media <name> is write protected.","Removable Flash Media <name> is write protected.  Check SD Card",1},
{"VFL1015",3,"Removable Flash Media <name> is writable.",0,0},
{"VFL1016",1,"Media not present for Removable Flash Media <name>.",0,0},
{"VFL1017",3,"Media is present for Removable Flash Media <name>.",0,0},
{"VFLA1000",3,"Removable Flash Media <name> is absent.",0,0},
{"VLT0100",2,"Processor module <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0101",1,"Processor module <name> voltage is less than the lower critical threshold.","Processor module <name> voltage is outside of range. Contact support",3},
{"VLT0102",2,"Processor module <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0103",1,"Processor module <name> voltage is greater than the upper critical threshold.","Processor module <name> voltage is outside of range . Contact support",3},
{"VLT0104",1,"Processor module <name> voltage is outside of range.","Processor module <name> voltage is outside of range. Contact support",3},
{"VLT0105",3,"Processor module <name> voltage is within range.",0,0},
{"VLT0200",2,"The system board <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0201",1,"The system board <name> voltage is less than the lower critical threshold.","The system board <name> voltage is outside of range. Contact support",3},
{"VLT0202",2,"The system board <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0203",1,"The system board <name> voltage is greater than the upper critical threshold.","The system board <name> voltage is outside of range. Contact support",3},
{"VLT0204",1,"The system board <name> voltage is outside of range.","System board voltage is outside of range. Contact support",3},
{"VLT0205",3,"The system board <name> voltage is within range.",0,0},
{"VLT0206",2,"The memory module <number> <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0207",1,"The memory module <number> <name> voltage is less than the lower critical threshold.","Memory module <number> <name> voltage is outside of range. Contact support",3},
{"VLT0208",2,"The memory module <number> <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0209",1,"The memory module <number> <name> voltage is greater than the upper critical threshold.","Memory module <number> <name> voltage is outside of range. Contact support",3},
{"VLT0210",1,"The memory module <number> <name> voltage is outside of range.","Memory module <number> <name> voltage is outside of range. Contact support",3},
{"VLT0211",3,"The memory module <number> <name> voltage is within range.",0,0},
{"VLT0212",2,"The disk drive bay <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0213",1,"The disk drive bay <name> voltage is less than the lower critical threshold.",0,0},
{"VLT0214",2,"The disk drive bay <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0215",1,"The disk drive bay <name> voltage is greater than the upper critical threshold.",0,0},
{"VLT0216",1,"The disk drive bay <name> voltage is outside of range.",0,0},
{"VLT0217",3,"The disk drive bay <name> voltage is within range.",0,0},
{"VLT0218",2,"The <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0219",1,"The <name> voltage is less than the lower critical threshold.","The <name> voltage is outside of range. Contact support",3},
{"VLT0220",2,"The <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0221",1,"The <name> voltage is greater than the upper critical threshold.","The <name> voltage is outside of range. Contact support",3},
{"VLT0222",1,"The <name> voltage is outside of range.","Internal voltage is outside of range. Contact support",3},
{"VLT0223",3,"The <name> voltage is within range.",0,0},
{"VLT0224",2,"The memory module <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0225",1,"The memory module <name> voltage is less than the lower critical threshold.","Memory module <name> voltage is outside of range. Contact support",3},
{"VLT0226",2,"The memory module <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0227",1,"The memory module <name> voltage is greater than the upper critical threshold.","Memory module <name> voltage is outside of range. Contact support",3},
{"VLT0228",1,"The memory module <name> voltage is outside of range.","Memory module <name> voltage is outside of range. Contact support",3},
{"VLT0229",3,"The memory module <name> voltage is within range.",0,0},
{"VLT0230",2,"The mezzanine card <number> <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0231",1,"The mezzanine card <number> <name> voltage is less than the lower critical threshold.",0,0},
{"VLT0232",2,"The mezzanine card <number> <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0233",1,"The mezzanine card <number> <name> voltage is greater than the upper critical threshold.",0,0},
{"VLT0234",1,"The mezzanine card <number> <name> voltage is outside of range.",0,0},
{"VLT0235",3,"The mezzanine card <number> <name> voltage is within range.",0,0},
{"VLT0300",2,"CPU <number> <name> voltage is less than the lower warning threshold.",0,0},
{"VLT0301",1,"CPU <number> <name> voltage is less than the lower critical threshold.","CPU <number> <name> voltage is outside of range.  Reseat CPU",3},
{"VLT0302",2,"CPU <number> <name> voltage is greater than the upper warning threshold.",0,0},
{"VLT0303",1,"CPU <number> <name> voltage is greater than the upper critical threshold.","CPU <number> <name> voltage is outside of range.  Reseat CPU",3},
{"VLT0304",1,"CPU <number> <name> voltage is outside of range.","CPU <number> <name> voltage is outside of range.  Reseat CPU",3},
{"VLT0305",3,"CPU <number> <name> voltage is within range.",0,0},
};
unsigned int EventTableSize = sizeof(EventTable)/sizeof(EventTable[0]); 
